# Generated by Django 4.0.4 on 2023-04-10 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikicontentarchive',
            name='folder_id',
        ),
        migrations.AddField(
            model_name='wikicontentarchive',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.wikifolder'),
        ),
        migrations.AlterField(
            model_name='wikicontent',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.wikifolder'),
        ),
    ]
