# Generated by Django 4.0.4 on 2023-04-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_remove_wikicontentarchive_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikicontent',
            name='is_updating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wikicontentarchive',
            name='approver1_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wikicontentarchive',
            name='approver2_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wikicontentarchive',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
