# Generated by Django 4.0.4 on 2023-05-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_alter_wikicontentarchive_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikicontentarchive',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
